[build]
  # This command installs server dependencies, then builds the client.
  command = "cd server && npm install && cd ../client && npm run build"
  
  # The base directory for the build command is the client folder
  base = "client/"
  
  # The folder to publish is the client's build output
  publish = "client/build/"
  
  # The location of our serverless function
  functions = "netlify/functions/"

# This rule proxies all API requests (like /api/auth/login) to our serverless function.
# THIS IS THE FIX for "nothing happens".
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# This rule fixes the "Page not found" error for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

