[build]
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Add this to install function dependencies automatically
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"